//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENT
{
    using System;
    
    
    public class NOTICIAS
    {
        
        private String mID;
        
        private String mID_ALERT;
        
        private String mTITULO;
        
        private String mAUTOR;
        
        private String mDESCRIPCION;
        
        private String mURL;
        
        private String mURLTOIMAGE;
        
        private DateTime mPUBLICADO;
        
        private String mFUENTE_ID;
        
        private String mFUENTE_NOMBRE;
        
        private Int32? mIdEstado;
        
        private Int32? mRelevante;
        
        private String mIdComuna;
        
        private Int32? mIdUsuarioAsignado;
        
        private DateTime mUltimaFechaModificacion;
        
        private Int32? mIdUsuarioAsignadoPor;
        
        private Int32? mIdSubCategoria;
        
        public virtual String ID
        {
            get
            {
                return this.mID;
            }
            set
            {
                this.mID = value;
            }
        }
        
        public virtual String ID_ALERT
        {
            get
            {
                return this.mID_ALERT;
            }
            set
            {
                this.mID_ALERT = value;
            }
        }
        
        public virtual String TITULO
        {
            get
            {
                return this.mTITULO;
            }
            set
            {
                this.mTITULO = value;
            }
        }
        
        public virtual String AUTOR
        {
            get
            {
                return this.mAUTOR;
            }
            set
            {
                this.mAUTOR = value;
            }
        }
        
        public virtual String DESCRIPCION
        {
            get
            {
                return this.mDESCRIPCION;
            }
            set
            {
                this.mDESCRIPCION = value;
            }
        }
        
        public virtual String URL
        {
            get
            {
                return this.mURL;
            }
            set
            {
                this.mURL = value;
            }
        }
        
        public virtual String URLTOIMAGE
        {
            get
            {
                return this.mURLTOIMAGE;
            }
            set
            {
                this.mURLTOIMAGE = value;
            }
        }
        
        public virtual DateTime PUBLICADO
        {
            get
            {
                return this.mPUBLICADO;
            }
            set
            {
                this.mPUBLICADO = value;
            }
        }
        
        public virtual String FUENTE_ID
        {
            get
            {
                return this.mFUENTE_ID;
            }
            set
            {
                this.mFUENTE_ID = value;
            }
        }
        
        public virtual String FUENTE_NOMBRE
        {
            get
            {
                return this.mFUENTE_NOMBRE;
            }
            set
            {
                this.mFUENTE_NOMBRE = value;
            }
        }
        
        public virtual Int32? IdEstado
        {
            get
            {
                return this.mIdEstado;
            }
            set
            {
                this.mIdEstado = value;
            }
        }
        
        public virtual Int32? Relevante
        {
            get
            {
                return this.mRelevante;
            }
            set
            {
                this.mRelevante = value;
            }
        }
        
        public virtual String IdComuna
        {
            get
            {
                return this.mIdComuna;
            }
            set
            {
                this.mIdComuna = value;
            }
        }
        
        public virtual Int32? IdUsuarioAsignado
        {
            get
            {
                return this.mIdUsuarioAsignado;
            }
            set
            {
                this.mIdUsuarioAsignado = value;
            }
        }
        
        public virtual DateTime UltimaFechaModificacion
        {
            get
            {
                return this.mUltimaFechaModificacion;
            }
            set
            {
                this.mUltimaFechaModificacion = value;
            }
        }
        
        public virtual Int32? IdUsuarioAsignadoPor
        {
            get
            {
                return this.mIdUsuarioAsignadoPor;
            }
            set
            {
                this.mIdUsuarioAsignadoPor = value;
            }
        }
        
        public virtual Int32? IdSubCategoria
        {
            get
            {
                return this.mIdSubCategoria;
            }
            set
            {
                this.mIdSubCategoria = value;
            }
        }
    }
}
